rsa.private-key=classpath:certs/private.pem
rsa.public-key=classpath:certs/public.pem
logging.level.org.springframework.security=TRACE
logging.level.org.springframework.jdbc=TRACE
server.error.include-message=always
